# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: uchiyama_development
  username: sugi511
  password:
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: uchiyama_test


# production:
#   <<: *default
#   database: db/production.sqlite3
